// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	dto "boilerplate/app/domain/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetAlbumInterface is an autogenerated mock type for the GetAlbumInterface type
type GetAlbumInterface struct {
	mock.Mock
}

// GetAlbumByID provides a mock function with given fields: ctx, id
func (_m *GetAlbumInterface) GetAlbumByID(ctx context.Context, id string) (dto.Album, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumByID")
	}

	var r0 dto.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.Album, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.Album); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAlbums provides a mock function with given fields: ctx
func (_m *GetAlbumInterface) GetAllAlbums(ctx context.Context) ([]dto.Album, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAlbums")
	}

	var r0 []dto.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.Album, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.Album); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetAlbumInterface creates a new instance of GetAlbumInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAlbumInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAlbumInterface {
	mock := &GetAlbumInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
