// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	dto "boilerplate/app/domain/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetJSONPostInterface is an autogenerated mock type for the GetJSONPostInterface type
type GetJSONPostInterface struct {
	mock.Mock
}

// GetFromThirdPartyAPI provides a mock function with given fields: ctx
func (_m *GetJSONPostInterface) GetFromThirdPartyAPI(ctx context.Context) ([]dto.Post, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFromThirdPartyAPI")
	}

	var r0 []dto.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.Post, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.Post); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetJSONPostInterface creates a new instance of GetJSONPostInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetJSONPostInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetJSONPostInterface {
	mock := &GetJSONPostInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
