// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	entity "boilerplate/app/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

// CreateAlbum provides a mock function with given fields: ctx, album
func (_m *RepositoryInterface) CreateAlbum(ctx context.Context, album entity.Album) (string, error) {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Album) (string, error)); ok {
		return rf(ctx, album)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Album) string); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Album) error); ok {
		r1 = rf(ctx, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlbumByID provides a mock function with given fields: ctx, id
func (_m *RepositoryInterface) GetAlbumByID(ctx context.Context, id string) (entity.Album, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumByID")
	}

	var r0 entity.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Album, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Album); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlbums provides a mock function with given fields: ctx
func (_m *RepositoryInterface) GetAlbums(ctx context.Context) ([]entity.Album, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbums")
	}

	var r0 []entity.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Album, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Album); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterface {
	mock := &RepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
