name: Go CI
on:
  push:
    branches:
      - "*"
  workflow_dispatch: # Adds manual trigger option

jobs:
  # # revisit lint
  # lint:
  #   name: Run Linting
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Check out the repository code
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     # Set up Go environment
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.21" # Adjust to your Go version

  #     # Install golangci-lint
  #     - name: Install golangci-lint
  #       run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

  #     # Run linting
  #     - name: Lint
  #       run: $(go env GOPATH)/bin/golangci-lint run ./... --verbose

  test:
    name: Run Unit Tests
    # Use the latest Ubuntu runner (GitHub-hosted virtual machine)
    runs-on: ubuntu-latest
    # Steps to execute
    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Specify your Go version here
      # Step 3: Install dependencies (optional, if your project uses modules)
      - name: Get Dependencies
        run: go mod download
      # Step 4: Run unit tests
      - name: Run Tests
        run: go test ./... -v

  build:
    name: Build Project
    runs-on: ubuntu-latest
    # needs: [lint, test] # Build only runs if lint and test succeed succeeds
    needs: [test] # Build only runs if lint and test succeed succeeds
    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Match the version from the test job

      # Install dependencies
      - name: Get Dependencies
        run: go mod download

      # Build the project
      - name: Build
        # run: go build -v ./... # build all
        run: go build -v -o ./bin ./cmd/album

      # Upload the built binary as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: album-binary
          path: |
            ./bin/album
